//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Документ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Документ()
        {
            this.Дополнительный_доступ = new HashSet<Дополнительный_доступ>();
            this.Превью = new HashSet<Превью>();
            this.Тег_файла = new HashSet<Тег_файла>();
        }
    
        public int Код_документа { get; set; }
        public int Код_типа { get; set; }
        public byte[] Документ1 { get; set; }
        public Nullable<System.DateTime> Дата_добавления { get; set; }
        public string Название_документа { get; set; }
        public int Код_раздела { get; set; }
    
        public virtual Раздел Раздел { get; set; }
        public virtual Тип_документа Тип_документа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Дополнительный_доступ> Дополнительный_доступ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Превью> Превью { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тег_файла> Тег_файла { get; set; }
    }
}
