//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Дополнительный_доступ
    {
        public int Код_доступа { get; set; }
        public int Код_профиля { get; set; }
        public int Код_документа { get; set; }
        public Nullable<System.DateTime> Дата_выдачи_доступа { get; set; }
    
        public virtual Вид_доступа Вид_доступа { get; set; }
        public virtual Документ Документ { get; set; }
        public virtual Профиль Профиль { get; set; }
    }
}
