//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Профиль
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Профиль()
        {
            this.Дополнительный_доступ = new HashSet<Дополнительный_доступ>();
        }
    
        public int Код_профиля { get; set; }
        public int Код_сотрудника { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int Код_роли { get; set; }
        public string Путь_загрузки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Дополнительный_доступ> Дополнительный_доступ { get; set; }
        public virtual Роль Роль { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
